services:

  backend:
    image: jonasrodriguez/vetlliga-backend:latest
    container_name: vetlliga-backend
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"      
    environment:
      - ADMIN_PASSWORD=changeme
      - JWT_SECRET=changeme
      - UPLOAD_DIR=/data
      - DB_URL=mariadb:3306
    depends_on:
      - mariadb
    networks:
      - app-network

  frontend:
    image: jonasrodriguez/vetlliga-frontend:latest
    container_name: vetlliga-frontend
    expose:
      - 80
    networks:
      - app-network

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: vetlliga
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PMA_HOST=mariadb
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "8008:80"
    networks:
      - app-network
    depends_on:
      - mariadb      

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./config/proxy:/data
      - ./config/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
